### ISSUE TITLE
Migration service SMS

### ISSUE THREAD

**Issue by drainuzzo** [Ernyoke/certified-aws-solutions-architect-professional#7]
AWS Server Migration Service (SMS) has been discontinued since 2022. However, the outdated information is still being presented in the SAP-C02 course by Cantrill (I attempted to report this issue without success).

To ensure accuracy, I suggest updating the Migration Guide to explicitly mention this discontinuation. While I am unsure if the exam content has been updated to reflect this change, it is important to note that as of 2022, Amazon MGN (Application Migration Service) is the recommended AWS service for migrating VMs.

**Comment by Ernyoke** [comment]
The following line from **AWS Application Migration Service (MGN)** says that AWS recommends MGN instead of SMS:
https://github.com/Ernyoke/certified-aws-solutions-architect-professional/blob/d513379db37283ed644038b0f147859542ee31d3/11-migrations/vm-migration.md?plain=1#L48

If you want to add anything more specific regarding this topic, please open a pull request.

There are may other services which have been discontinued and they are part of the exam (or part of exam questions set such as the ones from TutorialDojo or DigitalCloud). To give you a few examples: Opsworks, Simple Workflow Service (SWF), Snowmobile. I find it important to have this information persisted.

That being said, you are free to open a pull request to with any adjustments.
